name: Upload to container

on:
  release:
    types: [created]
jobs:
 upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create zip
        run: zip -r ./trigger_${{ env.RELEASE_VERSION }}.zip ./*
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        name: Uploading to Azure storage...
        with:
          source_dir: './'
          connection_string: ${{ secrets.CONNECTIONSTRING }}
          container_name: test
          extra_args: '--pattern *.zip'
          sync: false
